POST {{base_url}}/cart/2/line-items
Content-Type: application/json

{
  "product": 9,
  "quantity": 3
}

###

DELETE {{base_url}}/cart/2/line-items/1
Content-Type: application/json

###

GET {{base_url}}/cart/2/line-items
Content-Type: application/json

###
