POST {{base_url}}/products
Content-Type: application/json

{
  "title": "Super game",
  "price": {
    "amount": 12.3,
    "currency": "USD"
  }
}

###

DELETE {{base_url}}/products/10
Content-Type: application/json

###

GET {{base_url}}/products/10
Content-Type: application/json

###

PATCH {{base_url}}/products/9
Content-Type: application/json

{
  "title": "Super game 2",
  "price": {
    "amount": 12,
    "currency": "EUR"
  }
}

###

GET {{base_url}}/products?page=1
Content-Type: application/json

###