POST {{base_url}}/product
Content-Type: application/json

{
  "title": "Super game",
  "price": {
    "amount": 12.3,
    "currency": "USD"
  }
}

###

DELETE {{base_url}}/product/10
Content-Type: application/json

###
